### PR TITLE
list() does not include READONLY files

### PR DESCRIPTION
**Pull request by lbeschastny**
Right now `node-7z` list method ignores all files with any attributes except for `A` (compressed file) and `D` (directory). It happens because of [list.js#L23] regexp.

But real world archives could contain files with other attributes.

For example, I'm now working with archives containing read-only files, which result in `.R..A` attribute values.

I'm not sure what other attributes are included in 7zip archives, but I suppose it's something like:

    R   Read-only file attribute.
    S   System file attribute.
    H   Hidden file attribute.

  [list.js#L23]: https://github.com/quentinrossetti/node-7z/blob/master/lib/list.js#L23

### CODE REVIEW

**Comment by lbeschastny** [comment]
Slightly improved my previous fix and added proper tests.

The only problem here is that the test will fail without #14.

**Comment by lbeschastny** [comment]
Fixed tests by changing archive type from `7z` to `zip`.

**Comment by lbeschastny** [comment]
Rebased on master to fix merge conflicts.

**Comment by quentinrossetti** [comment]
Thank for reporting and fixing this bug. Just u few more bug-fixes and features testing and the new version of `node-7z` will be released on npm

**Pull request merged**
