### PR TITLE
list() does not return data for files with blank "Compressed" columns

### PR DESCRIPTION
**Pull request by curiousdannii**
list() does not return data for files with blank "Compressed" columns, which can be easily fixed with a small change to the regex.

An example of such an archive is https://archive.org/download/stackexchange/skeptics.stackexchange.com.7z [30M]
I don't know why it has blank columns, but it doesn't appear to be a corrupt archive.

### CODE REVIEW

**Comment by quentinrossetti** [comment]
Neat, thanks for contributing !
In order for your PR to be accepted it would be great to see a test for this particular case.

**Comment by curiousdannii** [comment]
I'll see if I can find a smaller archive with the same problem.

**Comment by curiousdannii** [comment]
@quentinrossetti I've added a test.

**Comment by lbeschastny** [comment]
Any plans on merging this PR?

**Comment by jvilk** [comment]
Please merge this PR. I immediately encountered this bug, which happens with any "solid" archive.

(In a "solid" archive, 7zip compresses multiple files into one block. 7zip cannot determine the compressed size of individual files, so it attributes the entire archive size to the first non-directory in the listing, and does not print a compressed size for subsequent files.)

If there is any concern about the 7z file used in the PR, you can simply compress two arbitrarily-sized text files on ULTRA settings and it will exhibit this issue.

**Comment by lbeschastny** [comment]
> If there is any concern about the 7z file used in the PR, you can simply compress two arbitrarily-sized text files on ULTRA settings and it will exhibit this issue.

@jvilk exactly what I did.

**Pull request merged**
