### PR TITLE
list sometimes cut file names somewhere in the middle

### PR DESCRIPTION
**Pull request by lbeschastny**
This bug was already reported and presumably fixed in #9:

> There was a bug in List where when getting list data from 7za it sometimes will end in the middle of a line and return a bad entry. Fixed regular expression to detect a complete line a bit better and added a buffer so the last incomplete line can be added to the beginning of the next progress data.

But I can confirm that the bug is still there. If 7zip stream ends in the middle of a file name then the fix isn't working.

I think, the last line should always be saved to the buffer, even it matches `regex`.

### CODE REVIEW

**Comment by lbeschastny** [comment]
Here is a fix (with a good, though somewhat complicated, test).

Another good thing is that coverage is `100%` again:

```
Statements   : 100% ( 209/209 )
Branches     : 100% ( 70/70 )
Functions    : 100% ( 52/52 )
Lines        : 100% ( 208/208 )
```

**Comment by lbeschastny** [comment]
Rebased on current master to resolve merge conflicts.

**Comment by lbeschastny** [comment]
Rebased again.

Not sure why git indicated merge conflicts here. `git rebase` went perfectly clear.

**Comment by lbeschastny** [comment]
@quentinrossetti, so, what about my PR?

**Comment by quentinrossetti** [comment]
based on the number of things to improve, i've decided to almost completely rewrite the lib.
more options will be available allowing a higher flexibility.
so for now all my dev time goes into that project and this branch will be no longer supported.

**Comment by lbeschastny** [comment]
@quentinrossetti so, does it mean that we're waiting for a brand new `node-7z@3` then?

**Comment by quentinrossetti** [comment]
yes exactly.
when i first wrote `node-7z` it was supposed to be a personal thing, used only by my projects and on sane, controlled archives.
the project eventually become more popular than i anticipated. and people started using it with archives from very different sources. basically the current version of `node-7z` is not designed for such uses.
also i wanted a more steam-oriented api and approach.

**Pull request closed without merging**
